apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: readiness-pod
  name: readiness-pod
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox--command
    name: readiness-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
