apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: small
  name: small
spec:
  containers:
  - command:
    - sh
    - -c
    - sleep 3600
    image: andreimihai/stress
    name: small
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
